version: "3.7"

services:

  flask1:
    build: ./flask1
    container_name: flask1
    restart: always
    environment: 
      - APP_NAME=Flask1
    expose:
      - 8080

  flask2:
    build: ./flask2
    container_name: flask2
    restart: always
    environment: 
       - APP_NAME=Flask2
    expose:
      - 8081

  nginx:
    build: ./nginx
    container_name: nginx 
    restart: always
    ports:
     - "80:80"

